<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\paragraphs\Entity\Paragraph;
use Drupal\prae_core\Controller\CoreController;
use Drupal\soc_core\Model\ContentType;

/**
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @return \Drupal\Core\Form\FormStateInterface
 */
function add_thnk_page_form_submit(array $form, FormStateInterface $form_state) {

  /** @var \Drupal\node\Entity\Node $node */
  $node = \Drupal\node\Entity\Node::load($form_state->get('nid'));
  if (!empty($node)) {
    $id_pargraph = $node->get('field_hero_paragraph')->target_id;
    $paragraph = Paragraph::load($id_pargraph);
    /** @var int $thumbnail_id */
    $thumbnail_id = $paragraph->get('field_thumbnail')->getValue()[0]['target_id'];

    /** @var \Drupal\Core\Url $url */
    $url = Url::fromRoute('node.add', [
      'node_type' => ContentType::CT_TY_P,
      'nidLp' => $node->id(),
      'title' => $node->get('title')->value,
      'thumbnail' => $thumbnail_id
    ]);
    return $form_state->setRedirectUrl($url);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
function soc_core_form_alter(&$form, FormStateInterface &$form_state, $form_id) {

  // Check if we are in the landing creation page
  if(!is_null($node = \Drupal::request()->attributes->get('node'))) {
    if(strcmp($node->gettype(), ContentType::CT_LANDING) == 0) {

      /** @var Array $nids */
      $nids = \Drupal::service('soc_core.node_api')->getAllThankYouPageFromLandingPage($node);
      $title = t('Create Thank you page');

      // Getting media id Thumbnail
      $id_pargraph = $node->get('field_hero_paragraph')->target_id;
      $paragraph = Paragraph::load($id_pargraph);
      $thumbnail_id = $paragraph->get('field_thumbnail')->getValue()[0]['target_id'];
      $attr_title = t('Create Thank you page');
      $url  = Url::fromRoute('node.add', [
        'node_type' => ContentType::CT_TY_P,
        'nidLp'=>$node->id(),
        'title' => $node->get('title')->value,
        'thumbnail' => $thumbnail_id
      ]);

      if (!empty($nids)) {
        $title = t('Editer Thank you Page');
        $url = Url::fromRoute('entity.node.edit_form', ['node' => current($nids)]);
        $attr_title = t('Editer Thank you page');
      }

      $form['actions']['button_thnk_p'] = [
        '#type' => 'link',
        // Add one to the current delta since it is zero-indexed.
        '#title' => $title,
        '#url' => $url,
        '#weight' => 99,
        '#attributes' => [
          'class' => 'button',
          'title' => $attr_title,
        ],
      ];
    }
  }

  // Check if we are in Add  new node ContentType
  if (!is_null(\Drupal::request()->attributes->get('node_type'))) {
    $node_type = \Drupal::request()->attributes->get('node_type')->id();
    $route = \Drupal::request()->attributes->get('_route');

    // If Added Content type is CT_LANDING
    // We add new link class button 'Save and create thank you page'
    if (strcmp($node_type, ContentType::CT_LANDING) == 0 && strcmp($route, 'node.add') == 0) {

      $title = t('Save and create thank you page');
      $form['actions']['button_thnk_p'] = [
        '#type' => 'submit',
        '#submit' => $form['actions']['submit']['#submit'],
        '#weight' => 99,
        '#value' => $title
      ];

      // We creat submit fonction if user click 'Save and create thank you page'
      $form['actions']['button_thnk_p']['#submit'][] = 'add_thnk_page_form_submit';
    }

    // We check if we are parameters for creating Thank you Page
    if (strcmp($node_type, ContentType::CT_TY_P) == 0 && strcmp($route, 'node.add') == 0) {

      if (!is_null(\Drupal::request()->get('nidLp'))) {
        \Drupal::service('cache.render')->invalidateAll();
        // Get target Landing Page
        $nid_lp = \Drupal::request()->get('nidLp');
        $form['field_landing_page']['widget'][0]['target_id']['#default_value'] = \Drupal\node\Entity\Node::load($nid_lp);

        // Get title of Landing page
        $title = \Drupal::request()->get('title');
        $form['title']['widget'][0]['value']['#default_value'] = $title;

        // We load Media Type
        $thumbnail_id = \Drupal::request()->get('thumbnail');
        $form['field_thumbnail']['widget'][0]['target_id']['#default_value'] = Drupal\media\Entity\Media::load($thumbnail_id);
      }
    }
  }
}

