display:
  default:
    display_options:
      fields:
        label:
          label: Label
        type:
          label: Type
      filters:
        label:
          expose:
            label: Label
          group_info:
            label: Label
        type:
          expose:
            label: Type
