display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        status:
          label: Status
        operations:
          label: Operations
      filters:
        status:
          group_info:
            label: Status
