display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      pager:
        options:
          tags:
            previous: '‹ previous'
            next: 'next ›'
            first: '« first'
            last: 'last »'
      fields:
        title:
          label: Title
        status:
          label: Status
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        status:
          expose:
            label: Status
