display:
  default:
    display_options:
      fields:
        title:
          label: Title
        status:
          label: Status
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        status:
          expose:
            label: Status
