display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        bundle:
          label: Type
        status:
          label: Status
        operations:
          label: Operations
      filters:
        bundle:
          expose:
            label: Type
