label: Files
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        filename:
          label: Name
        status:
          label: Status
      filters:
        status:
          expose:
            label: Status
      title: Files
  page_1:
    display_options:
      menu:
        title: Files
