display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        title:
          label: Title
        status:
          label: Status
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
        status:
          expose:
            label: Status
