display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Reset
      fields:
        type:
          label: Type
        link:
          label: Operations
      filters:
        type:
          expose:
            label: Type
