display:
  default:
    display_options:
      fields:
        title:
          label: Title
        operations:
          label: Operations
      filters:
        title:
          expose:
            label: Title
