<?php

/**
 * @file
 * Contains soc_default_images.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function soc_default_images_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the soc_default_images module.
    case 'help.page.soc_default_images':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Settings default images') . '</p>';
      return $output;

    default:
  }
}
