image: docker:stable

services:
  - docker:dind

variables:
  # For non-Kubernetes executors, we use tcp://docker:2375/
  # Provoque un changement dans la branche
  #DOCKER_HOST: tcp://localhost:2375/
  # DOCKER_HOST: "${HOSTNAME}-docker"
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_HOST: tcp://docker:2376/
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_BUILD_PATH: docker_image

stages:
  #  - build
  - sonarqube
  - behat
  - deploy

cache: &global_cache
  key: ${CI_JOB_NAME}
  paths:
    - vendor
    - web/node_modules

.behat_build_project: &behat_build_project
  artifacts:
    paths:
      - "${DOCKER_IMAGE_BUILD_PATH}/"
  variables:
    # No spaces.
    MINK_DRIVER_ARGS_WEBDRIVER: '["chrome",{"browserName":"chrome","chromeOptions":{"args":["--whitelisted-ips","--disable-gpu","--headless","--no-sandbox","--window-size=1920,1080"]}},"http://localhost:4444/wd/hub"]'
    APACHE_RUN_USER: "www-data"
    APACHE_RUN_GROUP: "www-data"
    # Selenium extra options, see
    # https://github.com/SeleniumHQ/docker-selenium#se_opts-selenium-configuration-options
    SE_OPTS: ""
  before_script:
    - mkdir -p "${DOCKER_IMAGE_BUILD_PATH}/"
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - cp ${CI_PROJECT_DIR}/docker-compose.example.gitlab-ci.yml ${CI_PROJECT_DIR}/docker-compose.yml
    - cp ${CI_PROJECT_DIR}/phing/example.build.properties.local ${CI_PROJECT_DIR}/phing/build.properties.local
    - cp ${CI_PROJECT_DIR}/tests/behat/behat.example.yml ${CI_PROJECT_DIR}/tests/behat/behat.local.yml
    - docker-compose up -d
    - docker-compose exec -u web -T web bash -c "cd /var/www/html/ && composer install"
    - docker-compose exec -u web -T web bash -c "cd /var/www/html/tests/behat && composer install"
    - docker-compose exec -u web -T web bash -c "cd /var/www/html/ && ./vendor/bin/phing install"

.build_project: &build_project
  artifacts:
    paths:
      - "${DOCKER_IMAGE_BUILD_PATH}/"
  variables:
    # No spaces.
    APACHE_RUN_USER: "www-data"
    APACHE_RUN_GROUP: "www-data"
    ENVIRONMENT: "develop"
  before_script:
    - mkdir -p "${DOCKER_IMAGE_BUILD_PATH}/"
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - cp ${CI_PROJECT_DIR}/docker-compose.example.gitlab-ci.yml ${CI_PROJECT_DIR}/docker-compose.yml
    - cp ${CI_PROJECT_DIR}/phing/example.build.properties.local ${CI_PROJECT_DIR}/phing/build.properties.local
    - docker-compose up -d
    - docker-compose exec -e ENVIRONMENT=${ENVIRONMENT} -u web -T web bash -c "cd /var/www/html/ && make install"
    - docker-compose exec -e ENVIRONMENT=${ENVIRONMENT} -u web -T web bash -c "cd /var/www/html/ && make set-kubernetes-configs"

# SonarQube Runner
sonarqube:
  stage: sonarqube
  tags:
    - actency
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://sonarqube.actency.fr
    SONAR_ANALYSIS_MODE: preview
  script:
    - gitlab-sonar-scanner -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.login=$SONARQUBE_ACCESS_KEY -Dsonar.gitlab.user_token=$GITLAB_ACCESS_KEY

# Behat tests from tests/ folder.
behat:
  stage: behat
  tags:
    - actency
  cache:
    # inherit all global cache settings
    <<: *global_cache
  extends:
    - .behat_build_project
  script:
    - docker-compose exec -u web -T web bash -c "cd /var/www/html && ./vendor/bin/phing behat:run -Dbehat.bin=tests/behat/bin/behat"

push-web-image:
  stage: deploy
  tags:
    - actency
  cache:
    # inherit all global cache settings
    <<: *global_cache
  extends:
    - .build_project
  script:
    - cd iaac && make push-web-image
  when: manual
