version: '2'
services:
  # web with xdebug - actency images
  web:
    # @see https://github.com/Actency/docker-apache-php
    build: ./docker/web
    environment:
      - SERVERNAME=socomec.com.loc
      - SERVERALIAS=socomec.com.loc
      - DOCUMENTROOT=web
      - DRUSH_VERSION=9
      - ENVIRONMENT=${ENVIRONMENT}
      - SOLR_HOST=solr
      - SOLR_PORT=8983
      - SOLR_COLLECTION=collection1
    volumes:
      - /builds/actency/prod/socomec/socomec.com/:/var/www/html
      - /builds/actency/prod/socomec/socomec.com/config/.bashrc:/var/www/.bashrc
    links:
      - database:mysql
      - mailhog
      - redis
      - solr
      - tika
    tty: true
    shm_size: 2G
    extra_hosts:
      - "socomec.com.loc:127.0.0.1"
      - "docker_host:10.10.10.254" # YOUR IP HERE
    hostname: "socomec.com.loc"

  # database container - actency images
  database:
    # @see https://github.com/Actency/docker-mysql
    image: actency/docker-mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlroot
      - MYSQL_DATABASE=socomec_com
      - MYSQL_USER=mysqlusr
      - MYSQL_PASSWORD=mysqlpwd

  # mailhog container - official images
  mailhog:
    image: mailhog/mailhog

  # redis container - official images
  redis:
    image: redis:latest

  # varnish v4 container - No official image exists, using the most used one.
  varnish:
    image: million12/varnish
    volumes:
      - ./config/varnish/default.vcl:/etc/varnish/custom.vcl
    links:
      - web:web-backend
    environment:
      - VCL_CONFIG=/etc/varnish/custom.vcl
      - VARNISHD_PARAMS=-p default_ttl=3600 -p default_grace=3600 -p http_max_hdr=512

  # solr container - actency images
  solr:
    image: actency/docker-solr:7.7.2
    volumes:
      - ./config/solr/:/opt/solr/server/solr/collection1/conf/

  # Tika server container - actency images
  tika:
    image: actency/docker-tika-server

  browser:
    image: selenium/standalone-chrome:3.14.0-europium
    shm_size: 2G
    links:
      - web
