# Schema for the configuration files of the Resource center page list.

soc_search.settings:
  type: config_object
  label: 'Search Settings'
  mapping:
    title:
      label: 'Title'
      type: label
      translatable: true
    title_searched:
      label: 'Page title with searched text'
      type: label
      translatable: true
    title_no_result:
      label: 'Page title without result'
      type: label
      translatable: true
    breadcrumb_title:
      label: 'Breadcrumb title'
      type: label
      translatable: true
    breadcrumb_title_searched:
      label: 'Breadcrumb title with searched text'
      type: label
      translatable: true
    placeholder:
      label: 'Placeholder'
      type: label
      translatable: true
    suggestion_title:
      label: 'Suggestion title'
      type: label
      translatable: true
    categorized_title:
      label: 'Categorized title'
      type: label
      translatable: true