# Schema for the configuration files of the Resource center page list.

soc_search.settings:
  type: config_object
  label: 'Search Settings'
  mapping:
    breadcrumb_title:
      label: 'Breadcrumb title'
      type: label
      translatable: true
    breadcrumb_title_searched:
      label: 'Breadcrumb title with searched text'
      type: label
      translatable: true
    placeholder:
      label: 'Placeholder'
      type: label
      translatable: true