<?php

/**
 * @file
 * Contains prae_core.module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_presave().
 *
 * Reset menu to default status when origin menu changed.
 */
function soc_menu_entity_update(EntityInterface $entity) {
  if (method_exists($entity, 'getTypedData') && method_exists($entity, 'getEntityTypeId')) {
    $entity_type = $entity->getEntityTypeId();
    switch ($entity_type) {
      case 'menu':
        Drupal::service('we_megamenu_deploy.importer')->importMenus(TRUE);
        break;
    }
  }
}
