display:
  default:
    display_options:
      fields:
        type:
          label: Type
        timestamp:
          label: Date
      filters:
        type:
          expose:
            label: Type
