display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
      fields:
        type:
          label: Type
        link:
          label: Actions
      filters:
        type:
          expose:
            label: Type
