display:
  default:
    display_options:
      fields:
        title:
          label: Titre
        status:
          label: État
        operations:
          label: Actions
      filters:
        title:
          expose:
            label: Titre
        status:
          expose:
            label: État
