label: Média
display:
  default:
    display_options:
      fields:
        thumbnail__target_id:
          label: Vignette
        bundle:
          label: Type
        uid:
          label: Auteur
        operations:
          label: Actions
      filters:
        bundle:
          expose:
            label: Type
        langcode:
          expose:
            label: Langue
      title: Média
  media_page_list:
    display_title: Média
    display_options:
      menu:
        title: Média
