display:
  default:
    display_options:
      fields:
        label:
          label: Étiquette
        type:
          label: Type
        id:
          label: 'Identifiant (ID)'
        changed:
          label: Modifié
        operations:
          label: Actions
      filters:
        label:
          expose:
            label: Étiquette
          group_info:
            label: Étiquette
        type:
          expose:
            label: Type
