display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
      fields:
        bundle:
          label: Type
        status:
          label: État
        operations:
          label: Actions
      filters:
        bundle:
          expose:
            label: Type
        langcode:
          expose:
            label: Langue
