display:
  default:
    display_options:
      fields:
        label:
          label: Étiquette
        id:
          label: 'Identifiant (ID)'
      filters:
        label:
          expose:
            label: Étiquette
          group_info:
            label: Étiquette
