display:
  default:
    display_options:
      fields:
        operations:
          label: Actions
      filters:
        langcode:
          expose:
            label: Langue
  page_unapproved:
    display_options:
      filters:
        langcode:
          expose:
            label: Langue
      fields:
        operations:
          label: Actions
