display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
      fields:
        type:
          label: Type
        link:
          label: Actions
      filters:
        type:
          expose:
            label: Type
