display:
  default:
    display_options:
      fields:
        bundle:
          label: Type
        operations:
          label: Actions
      filters:
        bundle:
          expose:
            label: Type
