display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: "‹\_précédent"
            next: "suivant\_›"
            first: "«\_premier"
            last: "dernier\_»"
      fields:
        title:
          label: Titre
          separator: ', '
        type:
          separator: ', '
        name:
          separator: ', '
        status:
          label: État
          separator: ', '
        publish_on:
          separator: ', '
        unpublish_on:
          separator: ', '
        operations:
          label: Actions
      filters:
        title:
          expose:
            label: Titre
        status:
          expose:
            label: État
    display_title: Maître
