display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
      fields:
        status:
          label: État
        operations:
          label: Actions
      filters:
        status:
          group_info:
            label: État
