display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ Précédent'
            next: 'Suivant ›'
      fields:
        title:
          label: Titre
        type:
          separator: ', '
        status:
          label: État
        operations:
          label: Actions
      filters:
        title:
          expose:
            label: Titre
        status:
          expose:
            label: État
    display_title: Maître
