display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Réinitialiser
      fields:
        subject:
          label: Objet
        name:
          label: Auteur
        operations:
          label: Actions
      filters:
        subject:
          expose:
            label: Objet
        langcode:
          expose:
            label: Langue
  page_unapproved:
    display_options:
      filters:
        subject:
          expose:
            label: Objet
        langcode:
          expose:
            label: Langue
      fields:
        subject:
          label: Objet
        name:
          label: Auteur
        operations:
          label: Actions
