display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Décalage
      fields:
        filesize:
          label: Taille
  page_2:
    display_options:
      pager:
        options:
          expose:
            offset_label: Décalage
