display:
  default:
    display_title: Maître
    display_options:
      exposed_form:
        options:
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      filters:
        status:
          expose:
            label: 'Statut de publication'
        name:
          expose:
            label: Nom
        bundle:
          expose:
            label: 'Type de média'
          group_info:
            label: 'Type de média'
      title: Média
  page:
    display_options:
      fields:
        name:
          separator: ', '
        edit_media:
          text: Modifier
        delete_media:
          text: Supprimer
  widget:
    display_options:
      filters:
        name:
          expose:
            label: Nom
  widget_table:
    display_options:
      fields:
        name:
          label: Nom
      filters:
        name:
          expose:
            label: Nom
