display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
      filters:
        langcode:
          expose:
            label: Langue
  page_unapproved:
    display_options:
      filters:
        langcode:
          expose:
            label: Langue
