display:
  default:
    display_options:
      filters:
        name:
          expose:
            label: Nom
  widget:
    display_title: Widget
    display_options:
      filters:
        name:
          expose:
            label: Nom
  widget_table:
    display_options:
      fields:
        name:
          label: Nom
      filters:
        name:
          expose:
            label: Nom
