display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
      filters:
        status:
          group_info:
            label: Publié
            group_items:
              1:
                title: Publié
              2:
                title: 'Non publié'
        name:
          expose:
            label: Nom
      title: Média
  page:
    display_options:
      menu:
        title: Média
  widget:
    display_options:
      filters:
        name:
          expose:
            label: Nom
  widget_table:
    display_options:
      fields:
        name:
          label: Nom
      filters:
        name:
          expose:
            label: Nom
