display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Décalage
      fields:
        type:
          label: Type
      filters:
        type:
          expose:
            label: Type
