display:
  default:
    display_options:
      fields:
        type:
          label: Type
        link:
          label: Actions
      filters:
        type:
          expose:
            label: Type
