display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
      fields:
        operations:
          label: Actions
      filters:
        langcode:
          expose:
            label: Langue
