label: Média
display:
  default:
    display_options:
      pager:
        options:
          expose:
            items_per_page_label: 'Éléments par page'
      fields:
        bundle:
          label: Type
        status:
          label: État
          settings:
            format_custom_true: Publié
            format_custom_false: 'Non publié'
      filters:
        bundle:
          expose:
            label: Type
        status:
          group_info:
            group_items:
              1:
                title: Publié
              2:
                title: 'Non publié'
        langcode:
          expose:
            label: Langue
      title: Média
  media_page_list:
    display_title: Média
