display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtrer
      fields:
        name:
          label: 'Nom d''utilisateur'
        status:
          label: État
        operations:
          label: Actions
      filters:
        status:
          group_info:
            label: État
