label: Contenu
display:
  default:
    display_options:
      fields:
        title:
          label: Titre
        type:
          label: 'Type de contenu'
        name:
          label: Auteur
        operations:
          label: Actions
      filters:
        title:
          expose:
            label: Titre
        type:
          expose:
            label: 'Type de contenu'
        langcode:
          expose:
            label: Langue
      title: Contenu
  page_1:
    display_options:
      menu:
        title: Contenu
      tab_options:
        title: Contenu
