display:
  default:
    display_options:
      fields:
        title:
          label: Tytuł
        status:
          label: Status
        operations:
          label: Operacje
      filters:
        title:
          expose:
            label: Tytuł
        status:
          expose:
            label: Status
