display:
  default:
    display_options:
      fields:
        type:
          label: Typ
        link:
          label: Operacje
      filters:
        type:
          expose:
            label: Typ
