display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Przesunięcie
      fields:
        filesize:
          label: Rozmiar
  page_2:
    display_options:
      pager:
        options:
          expose:
            offset_label: Przesunięcie
