display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Przesunięcie
      fields:
        type:
          label: Typ
      filters:
        type:
          expose:
            label: Typ
