display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtr
          reset_button_label: Resetuj
          exposed_sorts_label: 'Sortuj po'
          sort_asc_label: Rosnąco
          sort_desc_label: Malejąco
      pager:
        options:
          tags:
            previous: '‹ poprzednia'
            next: 'następna ›'
            first: '« pierwsza'
            last: 'ostatnia »'
      fields:
        node_bulk_form:
          action_title: Akcja
        title:
          label: Tytuł
          separator: ', '
        type:
          label: 'Rodzaj zawartości'
          separator: ', '
        name:
          label: Autor
          separator: ', '
        status:
          label: Status
          settings:
            format_custom_true: Opublikowane
            format_custom_false: Nieopublikowany
          separator: ', '
        publish_on:
          label: 'Publikuj dnia'
          separator: ', '
        unpublish_on:
          label: 'Anuluj publikację dnia'
          separator: ', '
        operations:
          label: Operacje
      filters:
        title:
          expose:
            label: Tytuł
        type:
          expose:
            label: 'Rodzaj zawartości'
        status:
          expose:
            label: Status
          group_info:
            label: 'Status publikacji'
            group_items:
              1:
                title: Opublikowane
              2:
                title: Nieopublikowany
        langcode:
          expose:
            label: Język
    display_title: Główny
  overview:
    display_options:
      menu:
        title: Zaplanowany
      tab_options:
        title: Zawartość
  user_page:
    display_options:
      menu:
        title: Zaplanowany
      tab_options:
        title: Zawartość
      arguments:
        uid:
          exception:
            title: Wszystko
