display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Przesunięcie
      fields:
        label:
          label: Etykieta
        type:
          label: Typ
      filters:
        label:
          expose:
            label: Etykieta
          group_info:
            label: Etykieta
        type:
          expose:
            label: Typ
