label: Media
display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Przesunięcie
      fields:
        bundle:
          label: Typ
      filters:
        bundle:
          expose:
            label: Typ
      title: Media
  media_page_list:
    display_title: Media
