display:
  default:
    display_options:
      fields:
        bundle:
          label: Typ
        status:
          label: Status
        operations:
          label: Operacje
      filters:
        bundle:
          expose:
            label: Typ
