display:
  default:
    display_options:
      fields:
        label:
          label: Etykieta
        type:
          label: Typ
        id:
          label: ID
        changed:
          label: Zmieniono
        operations:
          label: Operacje
      filters:
        label:
          expose:
            label: Etykieta
          group_info:
            label: Etykieta
        type:
          expose:
            label: Typ
