display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Resetuj
          exposed_sorts_label: 'Sortuj po'
          sort_asc_label: Rosnąco
          sort_desc_label: Malejąco
      pager:
        options:
          tags:
            previous: '‹ poprzednia'
            next: 'następna ›'
            first: '« pierwsza'
            last: 'ostatnia »'
      fields:
        title:
          label: Tytuł
          separator: ', '
        type:
          separator: ', '
        name:
          separator: ', '
        status:
          label: Status
          separator: ', '
        publish_on:
          separator: ', '
        unpublish_on:
          separator: ', '
        operations:
          label: Operacje
      filters:
        title:
          expose:
            label: Tytuł
        status:
          expose:
            label: Status
    display_title: Główny
