display:
  default:
    display_options:
      fields:
        name:
          label: 'Nazwa użytkownika'
        status:
          label: Status
        operations:
          label: Operacje
      filters:
        status:
          group_info:
            label: Status
