display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Resetuj
          exposed_sorts_label: 'Sortuj po'
          sort_asc_label: Rosnąco
          sort_desc_label: Malejąco
      pager:
        options:
          tags:
            previous: '‹ Poprzednia'
            next: 'Następna ›'
      fields:
        title:
          label: Tytuł
        type:
          separator: ', '
        status:
          label: Status
        operations:
          label: Operacje
      filters:
        title:
          expose:
            label: Tytuł
        status:
          expose:
            label: Status
    display_title: Główny
