label: Media
display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_asc_label: Asc
          sort_desc_label: Disc
      pager:
        options:
          expose:
            items_per_page_label: 'Voci per pagina'
            items_per_page_options_all_label: '- Tutto -'
            offset_label: Scostamento
          tags:
            previous: '‹ Precedente'
            next: 'Seguente ›'
      fields:
        thumbnail__target_id:
          separator: ', '
        name:
          separator: ', '
        bundle:
          label: Tipo
          separator: ', '
        uid:
          separator: ', '
        status:
          label: Stato
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: Operazioni
      filters:
        bundle:
          expose:
            label: Tipo
      title: Media
  media_page_list:
    display_title: Media
