display:
  default:
    display_options:
      fields:
        label:
          label: Etichetta
        type:
          label: Tipo
        changed:
          label: Modificato
        operations:
          label: Operazioni
      filters:
        label:
          expose:
            label: Etichetta
          group_info:
            label: Etichetta
        type:
          expose:
            label: Tipo
