display:
  default:
    display_options:
      fields:
        name:
          label: 'Nome utente'
        status:
          label: Stato
        operations:
          label: Operazioni
      filters:
        status:
          group_info:
            label: Stato
