display:
  default:
    display_options:
      fields:
        type:
          label: Tipo
        link:
          label: Operazioni
      filters:
        type:
          expose:
            label: Tipo
