display:
  default:
    display_options:
      fields:
        title:
          label: Titolo
        status:
          label: Stato
        operations:
          label: Operazioni
      filters:
        title:
          expose:
            label: Titolo
        status:
          expose:
            label: Stato
