display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Scostamento
      fields:
        filesize:
          label: Dimensione
  page_2:
    display_options:
      pager:
        options:
          expose:
            offset_label: Scostamento
