label: Media
display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Scostamento
      fields:
        bundle:
          label: Tipo
      filters:
        bundle:
          expose:
            label: Tipo
      title: Media
  media_page_list:
    display_title: Media
