display:
  default:
    display_options:
      fields:
        bundle:
          label: Tipo
        status:
          label: Stato
        operations:
          label: Operazioni
      filters:
        bundle:
          expose:
            label: Tipo
