display:
  default:
    display_title: Principale
    display_options:
      exposed_form:
        options:
          reset_button_label: Ripristina
          exposed_sorts_label: 'Ordina per'
          sort_asc_label: Asc
          sort_desc_label: Disc
      pager:
        options:
          expose:
            items_per_page_label: 'Voci per pagina'
            items_per_page_options_all_label: '- Tutto -'
            offset_label: Scostamento
      fields:
        label:
          label: Etichetta
          separator: ', '
        type:
          label: Tipo
          separator: ', '
        paragraphs__target_id:
          separator: ', '
        changed:
          label: Modificato
          separator: ', '
      filters:
        label:
          expose:
            label: Etichetta
          group_info:
            label: Etichetta
        type:
          expose:
            label: Tipo
