display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Scostamento
      fields:
        type:
          label: Tipo
      filters:
        type:
          expose:
            label: Tipo
