display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Desplazamiento
      fields:
        label:
          label: Etiqueta
        type:
          label: Tipo
      filters:
        label:
          expose:
            label: Etiqueta
          group_info:
            label: Etiqueta
        type:
          expose:
            label: Tipo
