display:
  default:
    display_options:
      fields:
        name:
          label: 'Nombre de usuario'
        status:
          label: Estado
        operations:
          label: Operaciones
      filters:
        status:
          group_info:
            label: Estado
