display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            previous: '‹ anterior'
            next: 'siguiente ›'
            first: '« primero'
            last: 'última »'
      fields:
        title:
          label: Título
          separator: ', '
        type:
          separator: ', '
        name:
          separator: ', '
        status:
          label: Estado
          separator: ', '
        publish_on:
          separator: ', '
        unpublish_on:
          separator: ', '
        operations:
          label: Operaciones
      filters:
        title:
          expose:
            label: Título
        status:
          expose:
            label: Estado
    display_title: Máster
