display:
  default:
    display_options:
      fields:
        label:
          label: Etiqueta
        type:
          label: Tipo
        id:
          label: ID
        changed:
          label: Modificado
        operations:
          label: Operaciones
      filters:
        label:
          expose:
            label: Etiqueta
          group_info:
            label: Etiqueta
        type:
          expose:
            label: Tipo
