display:
  default:
    display_options:
      fields:
        bundle:
          label: Tipo
        operations:
          label: Operaciones
      filters:
        bundle:
          expose:
            label: Tipo
