label: Multimedia
display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Desplazamiento
      fields:
        bundle:
          label: Tipo
      filters:
        bundle:
          expose:
            label: Tipo
      title: Multimedia
  media_page_list:
    display_title: Multimedia
