# Default values for drupal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: webfactory-prod

registry:
  name: agc-regis-credential
  images:
    drupal: socomec-web/drupal
    varnish: image-varnish-name

drupal:
  environment: develop
  version: 8
  name: webfactory-drupal
  nameOverride: ""
  fullnameOverride: ""
  username: admin
  password: admin
  ingress_hostname: webfactory-drupal-dev.dpk-soc-web-cl01.agoracalyce.net
  files_pv: drupal-develop-pv
  files_storage_class: webfactory-prod-fast01
  files_size: 5Gi
  disk_size: 10Gi
  replicaCount: 1
  service:
    port: 80

mysql:
  hostname: db_hostname

redis:
  master:
    hostname: redis_hostname
    port: 6379
  slave:
    hostname: redis_hostname
    port: 6379
