<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function soc_bookmarks_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Disable cache on bookmark form.
  if (strcmp($form_id, 'soc_bookmarks_bookmark_edit_form') == 0) {
    \Drupal::service('page_cache_kill_switch')->trigger();
  }
}

/**
 * Implements hook_theme().
 */
function soc_bookmarks_theme($existing, $type, $theme, $path) {
  return [
    'soc_bookmarks_custom_form' => [
      'render element' => 'form',
    ],
  ];
}
