uid: 92a799fc-ceb1-482a-b1c4-49b12914533e
langcode: en
status: true
dependencies:
  module:
    - addtoany
  theme:
    - socomec
id: addtoanybuttons
theme: socomec
region: content
weight: 0
provider: null
plugin: addtoany_block
settings:
  id: addtoany_block
  label: 'AddToAny buttons'
  provider: addtoany
  label_display: '0'
visibility: {  }
