definitions:
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__41':
    weight: -50
    menu_name: header
    parent: ''
    expanded: true
    enabled: true
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
