module:
  abjs: 0
  address: 0
  address_map_link: 0
  addtoany: 0
  addtocalendar: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  allow_iframed_site: 0
  anonymizer: 0
  auto_entitylabel: 0
  automated_cron: 0
  basic_auth: 0
  better_exposed_filters: 0
  better_normalizers: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_content_permissions: 0
  breakpoint: 0
  captcha: 0
  checklistapi: 0
  ckeditor: 0
  color: 0
  comment: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  config_translation: 0
  content_moderation: 0
  content_translation: 0
  contextual: 0
  ctools: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  default_content: 0
  default_content_deploy: 0
  dropdown_language: 0
  drush_language: 0
  ds_extras: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  entity: 0
  entity_reference_revisions: 0
  entity_share: 0
  entity_share_client: 0
  entity_share_cron: 0
  entity_usage: 0
  extra_field: 0
  facets: 0
  facets_pretty_paths: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  fontawesome: 0
  gdpr: 0
  gdpr_consent: 0
  gdpr_dump: 0
  gdpr_fields: 0
  gdpr_tasks: 0
  google_analytics: 0
  hal: 0
  help: 0
  history: 0
  hook_event_dispatcher: 0
  hotjar: 0
  image: 0
  image_effects: 0
  inline_entity_form: 0
  jsonapi: 0
  language: 0
  layout_discovery: 0
  libraries: 0
  link: 0
  link_target: 0
  locale: 0
  media: 0
  media_library: 0
  menu_breadcrumb: 0
  menu_link_attributes: 0
  menu_per_role: 0
  menu_ui: 0
  message: 0
  metatag: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  metatag_views: 0
  migrate: 0
  migrate_drupal: 0
  multiselect: 0
  node: 0
  options: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  queue_ui: 0
  quickedit: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  redis: 0
  remote_stream_wrapper: 0
  remote_stream_wrapper_widget: 0
  responsive_image: 0
  rest: 0
  scheduled_updates: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  smart_trim: 0
  soc_access_block: 0
  soc_addtoany: 0
  soc_basic_auth: 0
  soc_blocks_promotion: 0
  soc_bookmarks: 0
  soc_content_hub: 0
  soc_content_list: 0
  soc_core: 0
  soc_default_images: 0
  soc_eu_cookie_compliance: 0
  soc_events: 0
  soc_iframe_redirect: 0
  soc_job: 0
  soc_multisite: 0
  soc_nextpage: 0
  soc_pardot: 0
  soc_premium_content: 0
  soc_resource_center: 0
  soc_sales_locations: 0
  soc_search: 0
  soc_store_locator: 0
  soc_traceparts: 0
  soc_user: 0
  soc_views_news: 0
  soc_wishlist: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  taxonomy_menu: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  ultimate_cron: 0
  user: 0
  views_ui: 0
  we_megamenu: 0
  we_megamenu_deploy: 0
  workflows: 0
  youtube: 0
  ds: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
  eu_cookie_compliance: 1001
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  bootstrap_barrio: 0
  socomec: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
