definitions:
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__41':
    weight: -86
    menu_name: header
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.family.41'
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__6':
    weight: -87
    parent: 'menu_link_content:f138a7fe-23b6-4906-a9fd-e808bfa2bd94'
    menu_name: header
    enabled: true
    expanded: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__78':
    weight: -86
    parent: 'menu_link_content:f138a7fe-23b6-4906-a9fd-e808bfa2bd94'
    menu_name: header
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__68':
    weight: -85
    parent: 'menu_link_content:f138a7fe-23b6-4906-a9fd-e808bfa2bd94'
    menu_name: header
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__10':
    weight: -84
    parent: 'menu_link_content:f138a7fe-23b6-4906-a9fd-e808bfa2bd94'
    menu_name: header
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__7':
    weight: -87
    menu_name: header
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.family.6'
    expanded: true
    enabled: true
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
