definitions:
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__41':
    weight: -79
    menu_name: header
    parent: ''
    enabled: true
    expanded: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__6':
    weight: -86
    parent: 'menu_link_content:c4cec772-564f-47ad-bc3f-909fce54421e'
    menu_name: header
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__78':
    weight: -85
    parent: 'menu_link_content:c4cec772-564f-47ad-bc3f-909fce54421e'
    menu_name: header
    enabled: true
    expanded: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__68':
    weight: -84
    parent: 'menu_link_content:c4cec772-564f-47ad-bc3f-909fce54421e'
    menu_name: header
    expanded: true
    enabled: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__10':
    weight: -83
    parent: 'menu_link_content:c4cec772-564f-47ad-bc3f-909fce54421e'
    menu_name: header
    expanded: true
    enabled: true
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
