definitions:
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__41':
    weight: -79
    menu_name: header
    parent: ''
    enabled: true
    expanded: true
  'taxonomy_menu__menu_link:taxonomy_menu__menu_link__family__6':
    weight: -2
    menu_name: header
    parent: 'taxonomy_menu.menu_link:taxonomy_menu.menu_link.family.41'
    enabled: true
    expanded: true
_core:
  default_config_hash: o4bYR9ZupWb3AsOIizTUG4g-nu1mdJqA59UB7QT-ifQ
