disabled: false
field_template: false
ft-default: default
ft-show-colon: false
classes:
  region:
    - row
    - col-lg-1
    - col-lg-2
    - col-lg-3
    - col-lg-4
    - col-lg-5
    - col-lg-6
    - col-lg-7
    - col-lg-8
    - col-lg-9
    - col-lg-10
    - col-lg-11
    - col-lg-12
    - 'col-lg-1 ml-auto'
    - 'col-lg-2 ml-auto'
    - 'col-lg-3 ml-auto'
    - 'col-lg-4 ml-auto'
    - 'col-lg-5 ml-auto'
    - 'col-lg-6 ml-auto'
    - 'col-lg-7 ml-auto'
    - 'col-lg-8 ml-auto'
    - 'col-lg-9 ml-auto'
    - 'col-lg-10 ml-auto'
    - 'col-lg-11 ml-auto'
    - 'col-lg-12 ml-auto'
  field:
    - background-left-grey
    - background-right-grey
    - background-left-yellow
    - background-right-yellow
use_field_names: true
_core:
  default_config_hash: xfB0qOeoAomOThclNNokdKTrVwXLcXz13SU3-4a5-FY
