cookie_lifetime: 395
domain: ''
domains_option: 1
domains_list: ''
eu_only: null
eu_only_js: null
exclude_paths: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user\r\n/user/*\r\n/user/*/*"
exclude_admin_theme: false
langcode: en
popup_agreed:
  value: "<h2>Thank you for accepting cookies</h2>\r\n\r\n<p>You can now hide this message or find out more about cookies.</p>\r\n"
  format: socomec
popup_agree_button_message: 'OK, I agree'
popup_agreed_enabled: false
popup_bg_hex: ''
popup_clicking_confirmation: false
popup_scrolling_confirmation: false
popup_delay: 0
show_disagree_button: true
popup_disagree_button_message: 'More info'
popup_enabled: true
popup_find_more_button_message: 'More info'
popup_height: null
popup_hide_agreed: false
popup_hide_button_message: Hide
popup_info:
  value: "<p class=\"h3-blue\">We use cookies on this site to enhance your user experience</p>\r\n"
  format: socomec
mobile_popup_info:
  value: ''
  format: socomec
popup_info_template: new
mobile_breakpoint: 768
popup_link: '<front>'
popup_link_new_window: false
popup_position: false
fixed_top_position: true
popup_text_hex: ''
popup_width: ''
use_bare_css: true
disagree_do_not_show_popup: true
reload_page: true
cookie_name: ''
exclude_uid_1: false
better_support_for_screen_readers: false
use_mobile_message: false
method: categories
disagree_button_label: 'No, thanks'
disabled_javascripts: ''
whitelisted_cookies: "required:socomec_wishlist\r\nrequired:_gat_gtag_UA_156330380_1\r\nrequired:_gid\r\nrequired:_ga"
consent_storage_method: basic
withdraw_message:
  value: "<h2>We use cookies on this site to enhance your user experience</h2>\r\n\r\n<p>You have given your consent for us to set cookies.</p>\r\n"
  format: socomec
withdraw_action_button_label: 'Withdraw consent'
withdraw_tab_button_label: 'Privacy settings'
withdraw_enabled: false
cookie_categories: "required|Required|These cookies are essential to allow you to navigate the site and use its features. Without these cookies, basic services cannot be provided.\r\nstatistics|Statistics|These cookies allow the site to remember your preferences and offer you improved and personalized functions. For example where you are.\r\npreferences|Preferences|These cookies allow a website to analyze a visitor's behavior in order to be able to improve the site according to the visitor's needs.\r\ntargeting|Targeting|These cookies allow websites to personalize advertisements to suit your preferences or allow you to \"share\" content with friends via social networks such as Facebook, Twitter or similar service providers."
enable_save_preferences_button: true
save_preferences_button_label: 'Save preferences'
accept_all_categories_button_label: 'Accept all'
fix_first_cookie_category: true
select_all_categories_by_default: true
withdraw_button_on_info_popup: false
_core:
  default_config_hash: AiM4hI1afDR1mudSs5v2hwDmYDtq5-Nrf8HoxvCakR0
cookie_session: 0
domain_all_sites: false
uuid: e6484452-cb4c-41e9-8651-1d925fd12b3a
