entity_type_groups:
  node:
    landing_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      hreflang: hreflang
    thank_you_page:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      hreflang: hreflang
