channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: purger_varnish_1563b06bbe
    grants:
      - 0
      - 2
      - 3
