cookie_lifetime_days: '60'
page_title_en: 'My space'
page_title_fr: 'Mon espace'
_core:
  default_config_hash: 1I108rBH239V-HJU4cPaHhfDhBNrnItq9Ic5FiAKU88
bookmark_page_title: 'My documents'
bookmark_no_result: "<p class=\"text-align-center\">You do not have any documents saved.</p>\r\n\r\n<p class=\"text-align-center\"><a href=\"http://socomec.com.loc/resource-center\">Go to resource center</a></p>\r\n"
submit: 'Save configuration'
form_build_id: form-s2uMBVawbkQdJ_X2icF40Mzg-g52TvVx2KEvr9xdHWk
form_token: XWeMSRSCrocpxJIxbIXwYseKEXAJqG1yXSW6soNNJcc
form_id: soc_bookmarks_settings
op: 'Save configuration'
