base_url: 'https://preprod-socomecweb-api.nextpage.fr/com/'
auth_status: '1'
username: agence
password: ''
context_id: '1'
channel_extid: '##451471a6-4f2e-4395-820c-db907b1c945c'
endpoint_token: api/auth
endpoint_dicocarac: api/sdk/dicocarac/GetAll/2
endpoint_elementsandlinks: api/sdk/element/ElementsAndLinks
endpoint_descendantsandlinks: api/sdk/element/DescendantsAndLinks
endpoint_elementsbychartemplate: api/sdk/element/ElementsByCharTemplate
matching_libelle_dossier: LibelleDossier
CURLOPT_CONNECTTIMEOUT_MS: '5000'
CURLOPT_TIMEOUT_MS: '10000'
language_id_en: '1'
language_id_zh-cn: '1'
language_id_en-in: '1'
language_id_en-ch: '1'
language_id_en-gb: '1'
language_id_fr: '1'
language_id_fr-ch: '1'
language_id_de-ch: '1'
language_id_it: '1'
language_id_it-ch: '1'
language_id_es: '1'
language_id_fr-be: '1'
language_id_nl-be: '1'
language_id_de: '1'
language_id_en-us: '1'
language_id_pl: '1'
