base_url: 'https://preprod-socomec.nextpage.fr/'
username: ACY
password: actency2019!
context_id: '1'
language_id: '1'
endpoint_token: api/auth
endpoint_dicocarac: api/sdk-debug/dicocarac/GetAll
endpoint_elementsandlinks: api/sdk-ext/element/ElementsAndLinks
endpoint_descendantsandlinks: api/sdk-ext/element/DescendantsAndLinks
endpoint_elementsbychartemplate: api/sdk-ext/element/ElementsByCharTemplate
