<?php

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\Views;

/**
 * Implements hook_views_query_alter().
 *
 * Alter query of news page.
 * Exclude nid on display page_1 from display block_1
 *
 * @param \Drupal\views\ViewExecutable $view
 * @param \Drupal\views\Plugin\views\query\QueryPluginBase $query
 */
function soc_views_news_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() === 'news' && $view->getDisplay()->display['id'] === 'page_1') {
    $view_block = Views::getView('news');
    $view_block->setDisplay('block_1');
    $view_block->execute();
    // If the view returns results...
    if (!empty($view_block->result)) {
      $nid = $view_block->result[0]->_object->getEntity()->nid->value;
      if (!empty($nid)) {
        $query->addCondition('nid', $nid, '<>');
      }
    }
  }
}

/**
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function soc_views_news_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    if (($entity->getEntityTypeId() === 'taxonomy_term') && ($entity->bundle() === 'news_type')) {
      Drupal::messenger()->addMessage('custom message');
    }
  }
}
