<?php

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\node\Entity\Node;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\Views;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_views_query_alter().
 *
 * Alter query of news page.
 * Exclude nid on display page_1 from display block_1
 *
 * @param \Drupal\views\ViewExecutable $view
 * @param \Drupal\views\Plugin\views\query\QueryPluginBase $query
 */
function soc_views_news_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() === 'news' && $view->getDisplay()->display['id'] === 'page_1') {
    $view_block = Views::getView('news_highlight');
    if (!empty($view_block)) {
      if ($view_block->setDisplay('block_1')) {
        $view_block->execute();
        // If the view returns results...
        if (!empty($view_block->result)) {
          $nid = $view_block->result[0]->_object->getEntity()->nid->value;
          if (!empty($nid)) {
            $query->addCondition('nid', $nid, '<>');
          }
        }
        else {
          $view_block = Views::getView('news_highlight');
          if ($view_block->setDisplay('block_2')) {
            $view_block->execute();
            if (!empty($view_block->result)) {
              $nid = $view_block->result[0]->_object->getEntity()->nid->value;
              if (!empty($nid)) {
                $query->addCondition('nid', $nid, '<>');
              }
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_entity_delete().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 */
function soc_views_news_entity_delete(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity instanceof ContentEntityInterface) {
    if (($entity->getEntityTypeId() === 'taxonomy_term') && ($entity->bundle() === 'news_type')) {
      $ids = \Drupal::entityQuery('node')
        ->condition('type', 'news')
        ->condition('field_news_type', $entity->id())
        ->execute();
      $nodes = Node::loadMultiple($ids);
      if (count($nodes) === 0) {
        return;
      }
      $items = [];
      /** @var \Drupal\node\Entity\Node $node */
      foreach ($nodes as $node) {
        $items[] = $node->getTitle();
      }
      $renderer = \Drupal::service('renderer');
      $content['title'] = [
        '#type' => 'html_tag',
        '#value' => t('News pages to be modified after deletion of this category:'),
        '#tag' => 'h4',
      ];
      $content['list'] = ['#theme' => 'item_list', '#items' => $items];
      \Drupal::messenger()->addMessage($renderer->render($content));
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function soc_views_news_form_node_news_edit_form_alter(&$form, FormStateInterface $form_state, $form_id) {
 $form['sticky']['widget']['value']['#description'] = t('will only be displayed if a photo is attached');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function soc_views_news_form_node_news_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['sticky']['widget']['value']['#description'] = t('will only be displayed if a photo is attached');
}
