popup_agreed:
  value: '<h2>Vielen Dank für das Akzeptieren der Cookies</h2><p>Sie können diese Meldung jetzt ausblenden oder mehr über Cookies erfahren.</p>'
popup_agree_button_message: Akzeptieren
popup_disagree_button_message: 'Weitere Informationen'
popup_find_more_button_message: 'Weitere Informationen'
popup_hide_button_message: Ausblenden
popup_info:
  value: "<h3 class=\"h3-blue\">We use cookies on this site to enhance your user experience</h3>\r\n"
withdraw_message:
  value: "<h2>We use cookies on this site to enhance your user experience</h2>\r\n\r\n<p>You have given your consent for us to set cookies.</p>\r\n"
save_preferences_button_label: 'Einstellungen speichen'
accept_all_categories_button_label: 'Accept all'
