tips:
  search-api-index-form-introduction:
    body: 'Mit diesem Formular können Sie einen bestehenden Index bearbeiten oder einen neuen Index zu Ihrer Website hinzufügen. Indizes definieren einen Datensatz, der indiziert wird und dann durchsucht werden kann.'
  search-api-index-form-name:
    label: Index-Name
  search-api-index-form-datasources:
    label: Datenkquellen
  search-api-index-form-tracker:
    label: Tracker
    body: 'verfolgt, welche Elemente für den Index verfügbar sind und welche noch indiziert werden müssen. Das Ändern des Trackers eines bestehenden Index führt zur Neuindizierung aller Elemente.'
  search-api-index-form-server:
    label: Server
  search-api-index-form-description:
    label: Index-Beschreibung
  search-api-index-form-options:
    label: 'Erweiterte Optionen'
    body: 'Diese Optionen ermöglichen eine detailliertere Konfiguration des Indexverhaltens, können jedoch von unerfahrenen Benutzern normalerweise problemlos ignoriert werden.'
