label: 'Informationen über einen Index'
tips:
  search-api-index-introduction:
    label: 'Informationen über einen Index'
    body: 'Auf dieser Seite wird eine Zusammenfassung eines Suchindex und seines Status angezeigt.'
  search-api-index-index-status:
    label: 'Index Status'
    body: 'Dies ist eine Zusammenfassung darüber, wie viele Elemente in diesem Index bekannt sind und wie viele Elemente in ihrer neuesten Version indiziert wurden. Elemente, die noch nicht indiziert wurden, können von der Suchfunktion nicht gefunden werden.'
  search-api-index-status:
    label: Status
    body: 'Zeigt an, ob der Index aktuell aktiviert oder deaktiviert ist.'
  search-api-index-datasources:
    label: Datenkquellen
    body: 'Listet alle für diesen Index aktivierten Datenquellen auf.'
  search-api-index-tracker:
    label: Tracker
    body: 'Der Tracker, der vom Index verwendet wird. Standardmäßig ist nur („Standard") verfügbar.'
  search-api-index-server:
    label: Server
  search-api-index-server-index-status:
    label: Server-Indexstatus
    body: 'Bei aktivierten Indizes wird hier die Anzahl der Elemente angegeben, die tatsächlich vom Server abgerufen werden können. Warum diese Zahl von der unter "Indexstatus",  angegebenen Zahl abweichen kann, entnehmen Sie bitte der <a href="https://www.drupal.org/docs/8/modules/search-api/getting-started/frequently-asked-questions#server-index-status">Dokumentation</a> des Moduls.'
  search-api-index-cron-batch-size:
    label: 'Anzahl der Elemente, die bei jedem Cron-Lauf indiziert werden sollen.'
    body: 'Die Anzahl der Elemente, die während eines Cron-Laufes auf einmal indiziert werden.'
  search-api-index-tracking:
    label: 'Elemente für den Index erfassen'
  search-api-index-reindex:
    label: 'Alle Elemente zur Neuindizierung in die Warteschlange stellen'
  search-api-index-clear:
    label: 'Alle indizierten Daten löschen'
