display:
  default:
    display_options:
      fields:
        operations:
          label: Aktionen
  page_unapproved:
    display_options:
      fields:
        operations:
          label: Aktionen
