display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Offset
      fields:
        title:
          label: Titel
        operations:
          label: Aktionen
      filters:
        title:
          expose:
            label: Titel
