display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            previous: '‹ Vorherige Seite'
            next: 'Nächste Seite ›'
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
      fields:
        name:
          label: Benutzername
        status:
          label: Status
        operations:
          label: Aktionen
        mail:
          separator: ', '
      filters:
        status:
          group_info:
            label: Status
