display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Offset
      fields:
        operations:
          label: Aktionen
  page_unapproved:
    display_options:
      fields:
        operations:
          label: Aktionen
