display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Offset
      fields:
        label:
          label: Beschriftung
        type:
          label: Typ
        changed:
          label: Geändert
        operations:
          label: Aktionen
      filters:
        label:
          expose:
            label: Beschriftung
          group_info:
            label: Beschriftung
        type:
          expose:
            label: Typ
