display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
      fields:
        title:
          label: Titel
        type:
          label: Inhaltstyp
        name:
          label: Autor
        changed:
          label: Aktualisiert
        operations:
          label: Aktionen
      filters:
        title:
          expose:
            label: Titel
        type:
          expose:
            label: Inhaltstyp
        langcode:
          expose:
            label: Sprache
