label: Medien
display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Versatz
      fields:
        media_bulk_form:
          action_title: Aktion
        thumbnail__target_id:
          label: Miniaturbild
        bundle:
          label: Typ
        uid:
          label: Autor
        status:
          settings:
            format_custom_true: Veröffentlicht
            format_custom_false: 'Nicht veröffentlicht'
        changed:
          label: Aktualisiert
        operations:
          label: Aktionen
      filters:
        bundle:
          expose:
            label: Typ
        status:
          group_info:
            label: 'Status veröffentlicht'
            group_items:
              1:
                title: Veröffentlicht
              2:
                title: 'Nicht veröffentlicht'
        langcode:
          expose:
            label: Sprache
      title: Medien
      empty:
        area_text_custom:
          content: 'Keine Medien verfügbar.'
  media_page_list:
    display_title: Medien
