display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Offset
      fields:
        type:
          label: Typ
        link:
          label: Aktionen
      filters:
        type:
          expose:
            label: Typ
