display:
  default:
    display_options:
      fields:
        title:
          label: Titel
        status:
          label: Status
        operations:
          label: Aktionen
      filters:
        title:
          expose:
            label: Titel
        status:
          expose:
            label: Status
