display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Versatz
      fields:
        label:
          label: Beschriftung
        type:
          label: Typ
      filters:
        label:
          expose:
            label: Beschriftung
          group_info:
            label: Beschriftung
        type:
          expose:
            label: Typ
