display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Offset
      filters:
        status:
          expose:
            label: Veröffentlichungsstatus
        name:
          expose:
            label: Name
      title: Media
  page:
    display_options:
      fields:
        edit_media:
          text: Bearbeiten
  widget:
    display_options:
      filters:
        name:
          expose:
            label: Name
  widget_table:
    display_options:
      fields:
        name:
          label: Name
      filters:
        name:
          expose:
            label: Name
