display:
  default:
    display_options:
      fields:
        bundle:
          label: Typ
        operations:
          label: Aktionen
      filters:
        bundle:
          expose:
            label: Typ
