display:
  default:
    display_title: Master
    display_options:
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          expose:
            items_per_page_label: 'Elemente pro Seite'
            items_per_page_options_all_label: '- Alle -'
            offset_label: Offset
      filters:
        status:
          expose:
            label: Veröffentlichungsstatus
        name:
          expose:
            label: Name
        bundle:
          expose:
            label: Medientyp
          group_info:
            label: Medientyp
      title: Media
  page:
    display_options:
      fields:
        name:
          separator: ', '
        edit_media:
          text: Bearbeiten
        delete_media:
          text: Löschen
  widget:
    display_options:
      filters:
        name:
          expose:
            label: Name
  widget_table:
    display_options:
      fields:
        name:
          label: Name
      filters:
        name:
          expose:
            label: Name
