display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Offset
      fields:
        filename:
          label: Name
        filesize:
          label: Größe
        status:
          label: Status
      filters:
        status:
          expose:
            label: Status
  page_2:
    display_options:
      pager:
        options:
          expose:
            offset_label: Offset
