display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            previous: '‹ Vorherige Seite'
            next: 'Nächste Seite ›'
      fields:
        title:
          label: Titel
        type:
          separator: ', '
        status:
          label: Status
        operations:
          label: Aktionen
      filters:
        title:
          expose:
            label: Titel
        status:
          expose:
            label: Status
    display_title: Master
