display:
  default:
    display_options:
      exposed_form:
        options:
          reset_button_label: Zurücksetzen
          exposed_sorts_label: 'Sortieren nach'
          sort_asc_label: Aufsteigend
          sort_desc_label: Absteigend
      pager:
        options:
          tags:
            previous: '‹ vorherige Seite'
            next: 'nächste Seite ›'
            first: '« erste Seite'
            last: 'letzte Seite »'
      fields:
        title:
          label: Titel
          separator: ', '
        type:
          separator: ', '
        name:
          separator: ', '
        status:
          label: Status
          separator: ', '
        publish_on:
          separator: ', '
        unpublish_on:
          separator: ', '
        operations:
          label: Aktionen
      filters:
        title:
          expose:
            label: Titel
        status:
          expose:
            label: Status
    display_title: Master
