label: Medien
display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Versatz
      fields:
        bundle:
          label: Typ
      filters:
        bundle:
          expose:
            label: Typ
      title: Medien
  media_page_list:
    display_title: Medien
