display:
  default:
    display_options:
      fields:
        label:
          label: Beschriftung
        type:
          label: Typ
        id:
          label: ID
        changed:
          label: Geändert
        operations:
          label: Aktionen
      filters:
        label:
          expose:
            label: Beschriftung
          group_info:
            label: Beschriftung
        type:
          expose:
            label: Typ
