display:
  default:
    display_options:
      pager:
        options:
          expose:
            offset_label: Versatz
      title: Medien
  page:
    display_options:
      menu:
        title: Medien
