apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.drupal.name }}-pv
  labels:
    app: {{ .Values.drupal.name }}
    namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.drupal.disk_size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.drupal.files_storage_class }}
  nfs:
    path: /SSD_SOCOMEC_WEBFACTORY_NFS_01/SSD_SOCOMEC_WEBFACTORY_NFS_01_QTREE_01/{{ .Values.drupal.environment }}/files
    server: 10.67.68.20
